# Generated by Django 2.0 on 2018-02-27 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
